# Generated by Django 5.0.3 on 2024-04-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_commande_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='address',
            new_name='quartier',
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='ville',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
