# Generated by Django 5.0.3 on 2024-04-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_address_commande_quartier_commande_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='quartier',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ville',
        ),
    ]
